stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    # - apt update -y
    - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin

  script:
    - docker build -t $DOCKER_USERNAME/portfolio:$CI_PIPELINE_ID .
    - docker push $DOCKER_USERNAME/portfolio:$CI_PIPELINE_ID
  after_script:
    - echo Container Pushed to Docker Registory Successfully

test:
  stage: test
  dependencies:
    - build
  script:
    - echo "Test Successfully Complited"

deploy:
  stage: deploy
  dependencies:
    - test
  variables:
    DEPLOY_IMAGE: "$DOCKER_USERNAME/portfolio:$CI_PIPELINE_ID"

  before_script:
    - cat "$SSH_KEY" > dep.pem
    - chmod 400 dep.pem
    - mkdir -p ~/.ssh
    # - cat scripts/deploy_container.sh
    - ssh-keyscan "$DEP_IP" >> ~/.ssh/known_hosts
    - cp scripts/deploy_container.sh deploy_container.sh
    - ls
  # In this script we are passing the shill script as the input to the deployement server
  script:
    - cat deploy_container.sh | ssh -i "dep.pem" "$DEP_USER_NAME@$DEP_IP" 'bash -s' "$DEPLOY_IMAGE"

      # - ssh -i "dep.pem" "$DEP_USER_NAME@$DEP_IP" "bash -s < deploy_container.sh $DOCKER_USERNAME/flames"

