stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    # - apt update -y
    - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin

  script:
    - docker build -t $DOCKER_USERNAME/portfolio$CI_PIPELINE_ID .
    - docker push $DOCKER_USERNAME/portfolio$CI_PIPELINE_ID
  after_script:
    - echo Container Pushed to Docker Registory Successfully

test:
  stage: test
  dependencies:
    - build
  script:
    - echo "Test Successfully Complited"

deploy:
  stage: deploy
  dependencies:
    - test
  before_script:
    - echo "$SSH_KEY"" > dep.pem
    - chmod 400 dep.pem
    - ssh -i "dep.pem" "$DEP_USER_NAME"@"$DEP_IP" "docker rmi -f \$(docker images -q)"
    # - ssh -i "$SSH_KEY" $DEP_USER_NAME@$DEP_IP
    # - docker rmi -f $(docker images -q)
  script:
    - ssh -i "dep.pem" "$DEP_USER_NAME"@"$DEP_IP" "docker pull $DOCKER_USERNAME/portfolio:$CI_PIPELINE_ID"
    - ssh -i "dep.pem" "$DEP_USER_NAME"@"$DEP_IP" "docker run -d -p 80:5713 $DOCKER_USERNAME/portfolio:$CI_PIPELINE_ID"
