stages:
  - build
  - test
  - deploy

.build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    # - apt update -y
    - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin

  script:
    - docker build -t $DOCKER_USERNAME/portfolio:$CI_PIPELINE_ID .
    - docker push $DOCKER_USERNAME/portfolio:$CI_PIPELINE_ID
  after_script:
    - echo Container Pushed to Docker Registory Successfully

.test:
  stage: test
  dependencies:
    - build
  script:
    - echo "Test Successfully Complited"

deploy:
  stage: deploy
  # dependencies:
  #   - test
  before_script:
    - cat "$SSH_KEY" > dep.pem
    - chmod 400 dep.pem
    - mkdir -p ~/.ssh
    - ssh-keyscan "$DEP_IP" >> ~/.ssh/known_hosts
    - ssh -i "dep.pem" "$DEP_USER_NAME"@"$DEP_IP" "
      docker ps -q | xargs -r docker stop || true;
      docker ps -a -q | xargs -r docker rm || true;
      docker images -q | xargs -r docker rmi -f || true;"

  script:
    - ssh -i "dep.pem" "$DEP_USER_NAME"@"$DEP_IP" "docker pull prabakaran32/portfolio1790232500:tagname"
    - ssh -i "dep.pem" "$DEP_USER_NAME"@"$DEP_IP" "docker run -d -p 80:5713 prabakaran32/portfolio1790232500:tagname"
      # - ssh -i "dep.pem" "$DEP_USER_NAME"@"$DEP_IP" "docker pull $DOCKER_USERNAME/portfolio:$CI_PIPELINE_ID"
      # - ssh -i "dep.pem" "$DEP_USER_NAME"@"$DEP_IP" "docker run -d -p 80:5713 $DOCKER_USERNAME/portfolio:$CI_PIPELINE_ID"
